# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myagv_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.adaface_button = QtWidgets.QPushButton(self.centralwidget)
        self.adaface_button.setGeometry(QtCore.QRect(30, 50, 211, 41)) # 380, 50, 141, 41
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.adaface_button.setFont(font)
        self.adaface_button.setStyleSheet("QPushButton:pressed{\n"
                                    "   background-color:#c7c7d0;\n"
                                    "}\n"
                                    "")
        self.adaface_button.setObjectName("open_ros")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.person_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.person_comboBox.setGeometry(QtCore.QRect(270, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.person_comboBox.setFont(font)
        self.person_comboBox.setObjectName("comboBox")
        self.person_comboBox.addItem("")
        self.person_comboBox.addItem("")
        self.person_comboBox.addItem("")
        self.person_comboBox.addItem("")
        self.person_comboBox.addItem("")
        self.person_button = QtWidgets.QPushButton(self.centralwidget)
        self.person_button.setGeometry(QtCore.QRect(441, 50, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.person_button.setFont(font)
        self.person_button.setStyleSheet("QPushButton:pressed{\n"
                                         "   background-color:#c7c7d0;\n"
                                         "}\n"
                                         "")
        self.person_button.setObjectName("person_person")
        
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(30, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_log.setFont(font)
        self.label_log.setObjectName("label_log")
        self.textBrowser_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_log.setGeometry(QtCore.QRect(30, 140, 741, 56))
        self.textBrowser_log.setObjectName("textBrowser_log")

        self.label_debugger = QtWidgets.QLabel(self.centralwidget)
        self.label_debugger.setGeometry(QtCore.QRect(30, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_debugger.setFont(font)
        self.label_debugger.setObjectName("label_debugger")
        self.textBrowser_debugger = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_debugger.setGeometry(QtCore.QRect(30, 240, 741, 281))
        self.textBrowser_debugger.setObjectName("textBrowser_debugger")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adaface_button.setText(_translate("MainWindow", "start FR"))
        self.label.setText(_translate("MainWindow", "target person"))
        self.person_comboBox.setItemText(0, _translate("MainWindow", ""))
        self.person_comboBox.setItemText(1, _translate("MainWindow", "yeonju"))
        self.person_comboBox.setItemText(2, _translate("MainWindow", "minha"))
        self.person_comboBox.setItemText(3, _translate("MainWindow", "-"))
        self.person_comboBox.setItemText(4, _translate("MainWindow", "-"))
        self.person_button.setText(_translate("MainWindow", "reset"))
        self.label_log.setText(_translate("MainWindow", "Log: "))
        self.label_debugger.setText(_translate("MainWindow", "Debug: "))
